/**
 * HTML email body builders for phantom consolidator emails.
 */
import type { RawRow } from '@/types';

const BRAND_ORANGE = '#f97316';
const BRAND_BG = '#0f0f0f';
const BRAND_CARD = '#1a1a1a';
const BRAND_TEXT = '#f5f5f5';
const BRAND_MUTED = '#9ca3af';

function tableStyle(): string {
  return `border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:13px;`;
}

function thStyle(): string {
  return `background:${BRAND_ORANGE};color:#fff;padding:8px 10px;text-align:left;font-weight:bold;`;
}

function tdStyle(even: boolean): string {
  return `padding:7px 10px;border-bottom:1px solid #2a2a2a;background:${even ? '#222' : BRAND_CARD};color:${BRAND_TEXT};`;
}

function wrapper(content: string): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="background:${BRAND_BG};color:${BRAND_TEXT};font-family:Arial,sans-serif;margin:0;padding:24px;">
  <div style="max-width:900px;margin:0 auto;">
    <div style="border-left:4px solid ${BRAND_ORANGE};padding-left:16px;margin-bottom:24px;">
      <h1 style="color:${BRAND_ORANGE};margin:0;font-size:20px;">Phantom Consolidator</h1>
      <p style="color:${BRAND_MUTED};margin:4px 0 0;">OuterJoin Field Intelligence</p>
    </div>
    ${content}
    <p style="color:${BRAND_MUTED};font-size:11px;margin-top:32px;">
      This is an automated report generated by Phantom Consolidator.<br>
      Do not reply to this email.
    </p>
  </div>
</body>
</html>`.trim();
}

// ── Level 2 email: one per store ─────────────────────────────────────────────

export function buildL2StoreEmail(
  storeName: string,
  l2Name: string,
  rows: RawRow[],
  reportDate: string,
  mostRecentDateCol: string
): string {
  const rowsHtml = rows
    .map(
      (r, i) => `
      <tr>
        <td style="${tdStyle(i % 2 === 0)}">${r.CLIENT}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.Channel_ArticleCode}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.Client_Product_ID}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.Product_Description}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.Product_Brand}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r[mostRecentDateCol] ?? ''}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.Phantom_Indicator}</td>
      </tr>`
    )
    .join('');

  const content = `
    <h2 style="color:${BRAND_TEXT};margin-bottom:4px;">${storeName}</h2>
    <p style="color:${BRAND_MUTED};margin:0 0 16px;">
      Phantom Stock Report &mdash; ${reportDate} &mdash; ${rows.length} line(s)
    </p>
    <p>Hi ${l2Name},</p>
    <p style="margin-bottom:16px;">
      Please find attached the phantom stock report for <strong>${storeName}</strong> as at ${reportDate}.
      The products listed below have been flagged as phantom stock and require your attention.
    </p>
    <table style="${tableStyle()}">
      <thead>
        <tr>
          <th style="${thStyle()}">Client</th>
          <th style="${thStyle()}">Article Code</th>
          <th style="${thStyle()}">Product ID</th>
          <th style="${thStyle()}">Description</th>
          <th style="${thStyle()}">Brand</th>
          <th style="${thStyle()}">${mostRecentDateCol} SOH</th>
          <th style="${thStyle()}">Indicator</th>
        </tr>
      </thead>
      <tbody>${rowsHtml}</tbody>
    </table>`;

  return wrapper(content);
}

// ── Level 1 email: one per L2 rep (covering that rep's stores) ───────────────

export interface L1RepStores {
  l2Name: string;
  stores: { storeName: string; rowCount: number }[];
}

export function buildL1RepEmail(
  l1Name: string,
  rep: L1RepStores,
  reportDate: string
): string {
  const storeRows = rep.stores
    .map(
      (s, i) => `
      <tr>
        <td style="${tdStyle(i % 2 === 0)}">${s.storeName}</td>
        <td style="${tdStyle(i % 2 === 0)}">${s.rowCount}</td>
      </tr>`
    )
    .join('');

  const content = `
    <h2 style="color:${BRAND_TEXT};margin-bottom:4px;">Phantom Reports for ${rep.l2Name}</h2>
    <p style="color:${BRAND_MUTED};margin:0 0 16px;">Report Date: ${reportDate}</p>
    <p>Hi ${l1Name},</p>
    <p style="margin-bottom:16px;">
      Please find attached all phantom stock reports for your team member <strong>${rep.l2Name}</strong>
      as at ${reportDate}. Reports have also been sent directly to ${rep.l2Name}.
    </p>
    <table style="${tableStyle()}">
      <thead>
        <tr>
          <th style="${thStyle()}">Store Name</th>
          <th style="${thStyle()}">Phantom Lines</th>
        </tr>
      </thead>
      <tbody>${storeRows}</tbody>
    </table>`;

  return wrapper(content);
}

// ── Level 1 summary email: one per L1 (all their L2s) ───────────────────────

export interface L1SummaryRow {
  l2Name: string;
  storeCount: number;
  reportsSent: number;
}

export function buildL1SummaryEmail(
  l1Name: string,
  summaryRows: L1SummaryRow[],
  reportDate: string
): string {
  const rowsHtml = summaryRows
    .map(
      (r, i) => `
      <tr>
        <td style="${tdStyle(i % 2 === 0)}">${r.l2Name}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.storeCount}</td>
        <td style="${tdStyle(i % 2 === 0)}">${r.reportsSent}</td>
      </tr>`
    )
    .join('');

  const totalStores = summaryRows.reduce((s, r) => s + r.storeCount, 0);
  const totalReports = summaryRows.reduce((s, r) => s + r.reportsSent, 0);

  const content = `
    <h2 style="color:${BRAND_TEXT};margin-bottom:4px;">Phantom Report Summary</h2>
    <p style="color:${BRAND_MUTED};margin:0 0 16px;">Report Date: ${reportDate}</p>
    <p>Hi ${l1Name},</p>
    <p style="margin-bottom:16px;">
      Here is a summary of phantom stock reports distributed to your team for ${reportDate}.
    </p>
    <table style="${tableStyle()}">
      <thead>
        <tr>
          <th style="${thStyle()}">Representative (L2)</th>
          <th style="${thStyle()}">Stores</th>
          <th style="${thStyle()}">Reports Sent</th>
        </tr>
      </thead>
      <tbody>${rowsHtml}</tbody>
      <tfoot>
        <tr>
          <td style="padding:8px 10px;font-weight:bold;color:${BRAND_ORANGE};">Total</td>
          <td style="padding:8px 10px;font-weight:bold;color:${BRAND_ORANGE};">${totalStores}</td>
          <td style="padding:8px 10px;font-weight:bold;color:${BRAND_ORANGE};">${totalReports}</td>
        </tr>
      </tfoot>
    </table>`;

  return wrapper(content);
}
